### ISSUE TITLE
codereviewvideos.com can't open

### ISSUE THREAD

**Issue by ZoeSj** [codereviewvideos/symfony3-wallpaper-website-tutorial#2]
hell,i can't open your website from last night,what's wrong with site?Are u ok?

**Comment by codereviewvideos** [comment]
I'm super, thanks for asking :) 

I see no issues with downtime over the last 24 hours - not had any alerts, not seeing any faults on the servers. 

Were you seeing a specific error?

**Comment by ZoeSj** [comment]
> I'm super, thanks for asking :)
> 
> I see no issues with downtime over the last 24 hours - not had any alerts, not seeing any faults on the servers.
> 
> Were you seeing a specific error?

 i can use google,but can't scan your website ,i am learning the symfony4 from your website .Thanks for your video so much.
![image](https://user-images.githubusercontent.com/22183772/54277433-ce65d000-45ca-11e9-862e-48e808b04000.png)

**Comment by ZoeSj** [comment]
ahhhh  i can use it just now,i don't know what happened ,hahah  so happy.
